Return-Path: <linux-omap-owner@vger.kernel.org>
X-Original-To: lists+linux-omap@lfdr.de
Delivered-To: lists+linux-omap@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 41CA6517EEC
	for <lists+linux-omap@lfdr.de>; Tue,  3 May 2022 09:30:51 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S231761AbiECHeU (ORCPT <rfc822;lists+linux-omap@lfdr.de>);
        Tue, 3 May 2022 03:34:20 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:48040 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S232281AbiECHeO (ORCPT
        <rfc822;linux-omap@vger.kernel.org>); Tue, 3 May 2022 03:34:14 -0400
Received: from muru.com (muru.com [72.249.23.125])
        by lindbergh.monkeyblade.net (Postfix) with ESMTP id 40F34369FF;
        Tue,  3 May 2022 00:30:43 -0700 (PDT)
Received: from localhost (localhost [127.0.0.1])
        by muru.com (Postfix) with ESMTPS id BAA5C807E;
        Tue,  3 May 2022 07:27:25 +0000 (UTC)
Date:   Tue, 3 May 2022 10:30:40 +0300
From:   Tony Lindgren <tony@atomide.com>
To:     Arnd Bergmann <arnd@arndb.de>
Cc:     kernel test robot <lkp@intel.com>, kbuild-all@lists.01.org,
        Linux Memory Management List <linux-mm@kvack.org>,
        Russell King <linux@armlinux.org.uk>,
        linux-omap <linux-omap@vger.kernel.org>,
        Linux ARM <linux-arm-kernel@lists.infradead.org>,
        Linux Kernel Mailing List <linux-kernel@vger.kernel.org>
Subject: Re: [PATCH] ARM: dove: fix returnvar.cocci warnings
Message-ID: <YnDaINQbVtoJz1T3@atomide.com>
References: <202205031017.4TwMan3l-lkp@intel.com>
 <YnCXTPrbLhvfRVDm@e3a974050dc4>
 <CAK8P3a1xMeLa72YKMufdej6KguDwiSXtZmMqRxOt5B05x_fx3A@mail.gmail.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline
In-Reply-To: <CAK8P3a1xMeLa72YKMufdej6KguDwiSXtZmMqRxOt5B05x_fx3A@mail.gmail.com>
X-Spam-Status: No, score=-1.9 required=5.0 tests=BAYES_00,SPF_HELO_NONE,
        SPF_NONE,T_SCC_BODY_TEXT_LINE autolearn=ham autolearn_force=no
        version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-omap.vger.kernel.org>
X-Mailing-List: linux-omap@vger.kernel.org

* Arnd Bergmann <arnd@arndb.de> [220503 07:18]:
> On Tue, May 3, 2022 at 4:45 AM kernel test robot <lkp@intel.com> wrote:
> >
> > From: kernel test robot <lkp@intel.com>
> >
> > arch/arm/mach-omap2/dma.c:82:10-16: Unneeded variable: "errata". Return "0" on line 161
> >
> >
> >  Remove unneeded variable used to store return value.
> >
> > Generated by: scripts/coccinelle/misc/returnvar.cocci
> >
> > Reported-by: kernel test robot <lkp@intel.com>
> > Signed-off-by: kernel test robot <lkp@intel.com>
> 
> I checked the patch, and unfortunately it is wrong, the current code
> needs to stay.
> The problem is the SET_DMA_ERRATA() macro that accesses the
> local 'errata' variable.

Yeah this one keeps popping up. Maybe we can make SET_DMA_ERRATA
into a function or have it at least change it to set the errata
value.

Regards,

Tony
